{
  "swagger": "2.0",
  "info": {
    "title": "Bugdasht API - Admins",
    "description": "Bugdasht Backend Restful-API ( Admins Panel )",
    "version": "1.0"
  },
  "host": "185.79.157.27:3000",
  "basePath": "/v1/admins",
  "schemes": ["http"],
  "paths": {
    "/profile": {
      "put": {
        "tags": ["Profile"],
        "summary": "Update or change admin profile",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UpdateAdminProfile" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "درخواست شما با موفقعیت آپدیت شد"
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Profile"],
        "summary": "get admin profile",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "name": "کسری",
                  "phoneNumber": "09385667274",
                  "active": true,
                  "createdAt": null,
                  "updatedAt": null,
                  "role": {
                    "id": 1,
                    "name": "superAdmin"
                  },
                  "avatar": null,
                  "token": {
                    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmVOdW1iZXIiOiIwOTM4NTY2NzI3NCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY2NzUxODE4MSwiZXhwIjoxNjcxMTE4MTgxfQ.v7681wvFLpzeuVOp9oz8MrjbYHhJcw-aSALFrwH5Tts",
                    "expire": "2022-12-15T15:29:41.000Z"
                  }
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/": {
      "post": {
        "tags": ["Admins"],
        "summary": "create new admin",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/CreateOrUpdateAdmin" }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "examples": {
              "application/json": {
                "statusCode": 201,
                "data": {
                  "message": "درخواست شما با موفقعیت ثبت شد"
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Admins"],
        "summary": "Get all admins",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "search",
            "description": "search",
            "in": "query",
            "type": "string",
            "required": false
          },
          {
            "name": "page",
            "description": "set page number",
            "in": "query",
            "example": 0,
            "type": "int",
            "required": false
          },
          {
            "name": "pageSize",
            "description": "set pageSize",
            "example": 25,
            "in": "query",
            "type": "int",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "page": 1,
                  "pageSize": 25,
                  "totalCount": 3,
                  "totalPageLeft": 1,
                  "totalCountLeft": 25,
                  "admins": [
                    {
                      "id": 1,
                      "name": "کسری",
                      "phoneNumber": "09385667274",
                      "active": true,
                      "createdAt": null,
                      "updatedAt": null,
                      "role": {
                        "id": 1,
                        "name": "superAdmin"
                      }
                    },
                    {
                      "id": 2,
                      "name": "کسری",
                      "phoneNumber": "09385667272",
                      "active": true,
                      "createdAt": null,
                      "updatedAt": null,
                      "role": {
                        "id": 1,
                        "name": "superAdmin"
                      }
                    },
                    {
                      "id": 3,
                      "name": "کسری",
                      "phoneNumber": "09385667270",
                      "active": true,
                      "createdAt": null,
                      "updatedAt": null,
                      "role": {
                        "id": 1,
                        "name": "superAdmin"
                      }
                    }
                  ]
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/id/{id}": {
      "get": {
        "tags": ["Admins"],
        "summary": "find one of admin Data",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "name": "کسری",
                  "phoneNumber": "09385667274",
                  "active": true,
                  "createdAt": null,
                  "updatedAt": null
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Admins"],
        "summary": "delete one of admin Data",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 201,
                "data": {
                  "message": "درخواست شما با موفقعیت حذف شد"
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Admins"],
        "summary": "update or change one of admin Data",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/CreateOrUpdateAdmin" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "درخواست شما با موفقعیت ثبت شد"
                },
                "error": null
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/auth/login-confirm": {
      "post": {
        "tags": ["Auth"],
        "summary": "Confirm Login for open admin panel",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/LoginConfirm" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "name": "کسری خامسی",
                  "phoneNumber": "09385667274",
                  "active": true,
                  "createdAt": null,
                  "updatedAt": null,
                  "token": {
                    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmVOdW1iZXIiOiIwOTM4NTY2NzI3NCIsInR5cGUiOiJhZG1pbiIsImlhdCI6MTY3NDA5MzI1NywiZXhwIjoxNjc3NjkzMjU3fQ.zeaVQFECdcljeq831VPLpNuOfDrgjqkxdbeDCBlHAsk",
                    "expireAt": "2023-03-01T17:54:17.000Z"
                  }
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      }
    },

    "/organizations/projects/id/{id}": {
      "get": {
        "tags": ["Organizations-Projects"],
        "summary": "Get One Of Organization",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "name": "name",
                  "budget": 2000,
                  "isVip": false,
                  "lowPrice": 100,
                  "midPrice": 900,
                  "highPrice": 1000,
                  "ipAddress": "127.0.0.1",
                  "link": "link.com",
                  "domain": "domain.net",
                  "username": "username",
                  "paymentAmount": null,
                  "hasPayment": false,
                  "password": "password",
                  "adminId": null,
                  "status": "pending",
                  "canceledReason": null,
                  "isActive": true,
                  "description": "this is a description as long text",
                  "startAt": "2023-01-19T02:11:10.000Z",
                  "expireAt": "2023-01-19T02:11:10.000Z",
                  "createdAt": "2023-01-19T22:59:07.000Z",
                  "updatedAt": "2023-01-19T22:59:07.000Z"
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Organizations-Projects"],
        "summary": "Update One Of Organization",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/OrganizationsProjects" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "درخواست شما با موفقعیت آپدیت شد"
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      }
    },
    "/organizations/projects": {
      "get": {
        "tags": ["Organizations-Projects"],
        "summary": "Get All Organizations",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "status",
            "description": "set status to filter",
            "in": "query",
            "type": "string",
            "enum": ["canceled", "approved_for_payment", "approved", "pending"],
            "required": false
          },
          {
            "name": "page",
            "description": "set page number",
            "in": "query",
            "example": 0,
            "type": "int",
            "required": false
          },
          {
            "name": "pageSize",
            "description": "set pageSize",
            "example": 25,
            "in": "query",
            "type": "int",
            "required": false
          },
          {
            "name": "search",
            "description": "search",
            "in": "query",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "page": 1,
                  "pageSize": 5,
                  "totalCount": 1,
                  "totalPageLeft": 0,
                  "totalCountLeft": 0,
                  "organizationsProjects": [
                    {
                      "id": 1,
                      "name": "name",
                      "budget": 2000,
                      "isVip": false,
                      "lowPrice": 100,
                      "midPrice": 900,
                      "highPrice": 1000,
                      "ipAddress": "127.0.0.1",
                      "link": "link.com",
                      "domain": "domain.net",
                      "username": "username",
                      "paymentAmount": null,
                      "hasPayment": false,
                      "password": "password",
                      "adminId": null,
                      "status": "pending",
                      "canceledReason": null,
                      "isActive": true,
                      "description": "this is a description as long text",
                      "startAt": "2023-01-19T02:11:10.000Z",
                      "expireAt": "2023-01-19T02:11:10.000Z",
                      "createdAt": "2023-01-19T22:59:07.000Z",
                      "updatedAt": "2023-01-19T22:59:07.000Z"
                    }
                  ]
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },

    "/organizations/id/{id}": {
      "get": {
        "tags": ["Organizations"],
        "summary": "Get One Of Organization",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "name": "کسری خامسی",
                  "phoneNumber": "09385667274",
                  "active": true,
                  "createdAt": null,
                  "updatedAt": null,
                  "token": {
                    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmVOdW1iZXIiOiIwOTM4NTY2NzI3NCIsInR5cGUiOiJhZG1pbiIsImlhdCI6MTY3NDA5MzI1NywiZXhwIjoxNjc3NjkzMjU3fQ.zeaVQFECdcljeq831VPLpNuOfDrgjqkxdbeDCBlHAsk",
                    "expireAt": "2023-03-01T17:54:17.000Z"
                  }
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Organizations"],
        "summary": "Update One Of Organization",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/Organizations" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "درخواست شما با موفقعیت آپدیت شد"
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Organizations"],
        "summary": "Delete Organization Account",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "با موفقعیت حذف شد"
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      }
    },
    "/organizations": {
      "get": {
        "tags": ["Organizations"],
        "summary": "Get All Organizations",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "page",
            "description": "set page number",
            "in": "query",
            "example": 0,
            "type": "int",
            "required": false
          },
          {
            "name": "pageSize",
            "description": "set pageSize",
            "example": 25,
            "in": "query",
            "type": "int",
            "required": false
          },
          {
            "name": "search",
            "description": "search",
            "in": "query",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "page": 1,
                  "pageSize": 5,
                  "totalCount": 1,
                  "totalPageLeft": 0,
                  "totalCountLeft": 0,
                  "organizations": [
                    {
                      "id": 1,
                      "name": "Kasra",
                      "delegateName": "این یک نام نماینده است",
                      "phoneNumber": "09385667274",
                      "email": "kasra@gmail.com",
                      "username": null,
                      "password": null,
                      "adminId": null,
                      "status": "pending",
                      "createdAt": "2023-01-19T02:11:10.000Z",
                      "updatedAt": "2023-01-19T02:11:10.000Z"
                    }
                  ]
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/hunters/id/{id}": {
      "get": {
        "tags": ["Hunters"],
        "summary": "Get One Of Hunters",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "name": "کسری خامسی",
                  "phoneNumber": "09385667274",
                  "active": true,
                  "createdAt": null,
                  "updatedAt": null,
                  "token": {
                    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmVOdW1iZXIiOiIwOTM4NTY2NzI3NCIsInR5cGUiOiJhZG1pbiIsImlhdCI6MTY3NDA5MzI1NywiZXhwIjoxNjc3NjkzMjU3fQ.zeaVQFECdcljeq831VPLpNuOfDrgjqkxdbeDCBlHAsk",
                    "expireAt": "2023-03-01T17:54:17.000Z"
                  }
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Hunters"],
        "summary": "Update One Of Hunters",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/Hunters" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "درخواست شما با موفقعیت آپدیت شد"
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Hunters"],
        "summary": "Delete Hunters Account",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "با موفقعیت حذف شد"
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      }
    },
    "/hunters": {
      "get": {
        "tags": ["Hunters"],
        "summary": "Get All Hunters",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "page",
            "description": "set page number",
            "in": "query",
            "example": 0,
            "type": "int",
            "required": false
          },
          {
            "name": "pageSize",
            "description": "set pageSize",
            "example": 25,
            "in": "query",
            "type": "int",
            "required": false
          },
          {
            "name": "search",
            "description": "search",
            "in": "query",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "page": 1,
                  "pageSize": 5,
                  "totalCount": 5,
                  "totalPageLeft": 0,
                  "totalCountLeft": 0,
                  "hunters": [
                    {
                      "id": 5,
                      "profileImage": null,
                      "nationalCode": 22922991,
                      "nickName": null,
                      "firstName": "kasra",
                      "lastName": "khamesi",
                      "birthDate": "Birth Date",
                      "phoneNumber": "09385667274",
                      "email": null,
                      "shebaNumber": null,
                      "twitter": null,
                      "linkedin": null,
                      "bugCrowd": null,
                      "hackerOne": null,
                      "description": null,
                      "balance": 0,
                      "createdAt": "2023-01-19T02:26:19.000Z",
                      "updatedAt": "2023-01-19T02:26:19.000Z"
                    },
                    {
                      "id": 4,
                      "profileImage": null,
                      "nationalCode": 22922991,
                      "nickName": null,
                      "firstName": "kasra",
                      "lastName": "khamesi",
                      "birthDate": "Birth Date",
                      "phoneNumber": "09385667274",
                      "email": null,
                      "shebaNumber": null,
                      "twitter": null,
                      "linkedin": null,
                      "bugCrowd": null,
                      "hackerOne": null,
                      "description": null,
                      "balance": 0,
                      "createdAt": "2023-01-19T02:26:03.000Z",
                      "updatedAt": "2023-01-19T02:26:03.000Z"
                    }
                  ]
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          }
        }
      }
    },
    "/organizations/projects/id/{id}/reports": {
      "get": {
        "tags": ["Project Report"],
        "summary": "get reports",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "adminResponseStatus",
            "description": "set status to filter",
            "in": "query",
            "type": "string",
            "enum": ["rejected", "approved", "pending"],
            "required": false
          },
          {
            "name": "search",
            "description": "search",
            "in": "query",
            "type": "string",
            "required": false
          },
          {
            "name": "page",
            "description": "set page number",
            "in": "query",
            "example": 0,
            "type": "int",
            "required": false
          },
          {
            "name": "pageSize",
            "description": "set pageSize",
            "example": 25,
            "in": "query",
            "type": "int",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "page": 1,
                  "pageSize": 5,
                  "totalCount": 1,
                  "totalPageLeft": 0,
                  "totalCountLeft": 0,
                  "projectsReports": [
                    {
                      "id": 1,
                      "organizationId": 1,
                      "hunterId": 1,
                      "bugTitle": "asd",
                      "organizationsProjectId": 1,
                      "domainOrIp": "asd",
                      "cvss": "asd",
                      "cve": "asd",
                      "vector": "asd",
                      "video": "localhost:3000/v1/f1_3_( 4efe5c386449389794a6ee601c38983d38161941-144p.mp4 ).mp4",
                      "picOne": null,
                      "picTwo": null,
                      "bugDescription": "asd",
                      "solutionDescription": "a",
                      "adminId": null,
                      "adminResponseStatus": "pending",
                      "rejectedReason": null,
                      "bugLevel": null,
                      "payableAmount": null,
                      "createdAt": "2023-01-21T16:05:51.000Z",
                      "updatedAt": "2023-01-21T16:05:51.000Z",
                      "hunter": {
                        "nickName": "khamesi"
                      }
                    }
                  ]
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      }
    },
    "/hunters/reports/id/{id}": {
      "get": {
        "tags": ["Project Report"],
        "summary": "get report",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "organizationId": 1,
                  "hunterId": 1,
                  "bugTitle": "asd",
                  "organizationsProjectId": 1,
                  "domainOrIp": "asd",
                  "cvss": "asd",
                  "cve": "asd",
                  "vector": "asd",
                  "video": "localhost:3000/v1/f1_3_( 4efe5c386449389794a6ee601c38983d38161941-144p.mp4 ).mp4",
                  "picOne": null,
                  "picTwo": null,
                  "bugDescription": "asd",
                  "solutionDescription": "a",
                  "adminId": null,
                  "adminResponseStatus": "pending",
                  "rejectedReason": null,
                  "bugLevel": null,
                  "payableAmount": null,
                  "createdAt": "2023-01-21T16:05:51.000Z",
                  "updatedAt": "2023-01-21T16:05:51.000Z",
                  "project": {
                    "id": 1,
                    "organizationId": 1,
                    "name": "name",
                    "budget": 2000,
                    "isVip": false,
                    "lowPrice": 100,
                    "midPrice": 900,
                    "highPrice": 1000,
                    "ipAddress": "127.0.0.1",
                    "link": "link.com",
                    "domain": "domain.net",
                    "username": "username",
                    "paymentAmount": null,
                    "hasPayment": false,
                    "password": "password",
                    "adminId": null,
                    "status": "pending",
                    "canceledReason": null,
                    "isActive": true,
                    "description": "this is a description as long text",
                    "startAt": "2023-01-19T02:11:10.000Z",
                    "expireAt": "2023-01-19T02:11:10.000Z",
                    "createdAt": "2023-01-21T16:04:08.000Z",
                    "updatedAt": "2023-01-21T16:04:08.000Z"
                  },
                  "hunter": {
                    "nickName": "khamesi"
                  }
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Project Report"],
        "summary": "update report",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/UpdateReport" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "message": "درخواست شما با موفقعیت آپدیت شد"
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      }
    },
    "/hunters/reports": {
      "get": {
        "tags": ["Project Report"],
        "summary": "get reports",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "authorization",
            "description": "Bearer Token",
            "in": "header",
            "type": "string",
            "required": true
          },
          {
            "name": "search",
            "description": "search",
            "in": "query",
            "type": "string",
            "required": false
          },
          {
            "name": "adminResponseStatus",
            "description": "set status to filter",
            "in": "query",
            "type": "string",
            "enum": ["rejected", "approved", "pending"],
            "required": false
          },
          {
            "name": "page",
            "description": "set page number",
            "in": "query",
            "example": 0,
            "type": "int",
            "required": false
          },
          {
            "name": "pageSize",
            "description": "set pageSize",
            "example": 25,
            "in": "query",
            "type": "int",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "page": 1,
                  "pageSize": 5,
                  "totalCount": 1,
                  "totalPageLeft": 0,
                  "totalCountLeft": 0,
                  "projectsReports": [
                    {
                      "id": 1,
                      "organizationId": 1,
                      "bugTitle": "asd",
                      "organizationsProjectId": 1,
                      "domainOrIp": "asd",
                      "cvss": "asd",
                      "cve": "asd",
                      "vector": "asd",
                      "video": "localhost:3000/v1/f1_3_( 4efe5c386449389794a6ee601c38983d38161941-144p.mp4 ).mp4",
                      "picOne": null,
                      "picTwo": null,
                      "bugDescription": "asd",
                      "solutionDescription": "a",
                      "adminId": null,
                      "adminResponseStatus": "pending",
                      "rejectedReason": null,
                      "bugLevel": null,
                      "payableAmount": null,
                      "createdAt": "2023-01-21T16:05:51.000Z",
                      "updatedAt": "2023-01-21T16:05:51.000Z",
                      "project": {
                        "id": 1,
                        "organizationId": 1,
                        "name": "name",
                        "budget": 2000,
                        "isVip": false,
                        "lowPrice": 100,
                        "midPrice": 900,
                        "highPrice": 1000,
                        "ipAddress": "127.0.0.1",
                        "link": "link.com",
                        "domain": "domain.net",
                        "username": "username",
                        "paymentAmount": null,
                        "hasPayment": false,
                        "password": "password",
                        "adminId": null,
                        "status": "pending",
                        "canceledReason": null,
                        "isActive": true,
                        "description": "this is a description as long text",
                        "startAt": "2023-01-19T02:11:10.000Z",
                        "expireAt": "2023-01-19T02:11:10.000Z",
                        "createdAt": "2023-01-21T16:04:08.000Z",
                        "updatedAt": "2023-01-21T16:04:08.000Z"
                      },
                      "hunter": {
                        "nickName": "khamesi"
                      }
                    }
                  ]
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "http",
      "scheme": "bearer",
      "bearerFormat": "JWT",
      "in": "header"
    }
  },
  "definitions": {
    "UpdateReport": {
      "type": "object",
      "properties": {
        "bugLevel": {
          "type": "string",
          "example": "low",
          "enum": ["low", "mid", "high"]
        },
        "adminResponseStatus": {
          "type": "string",
          "example": "approved",
          "enum": ["pending", "approved", "rejected"]
        },
        "rejectReason": { "type": "string", "example": "اگر دلیل در دارد" }
      }
    },
    "LoginConfirm": {
      "type": "object",
      "properties": {
        "phoneNumber": { "type": "string", "example": "09385667274" },
        "password": { "type": "string", "example": "superadmin" }
      }
    },
    "Organizations": {
      "type": "object",
      "properties": {
        "username": { "type": "string", "example": "ThisIsUsername" },
        "password": { "type": "string", "example": "password" },
        "status": {
          "type": "string",
          "example": "approved",
          "enum": ["pending", "approved", "rejected"]
        }
      }
    },
    "Hunters": {
      "type": "object",
      "properties": {
        "nationalCode": { "type": "string", "example": "2101231233" },
        "nickName": { "type": "string", "example": "nick Name" },
        "firstName": { "type": "string", "example": "first Name" },
        "lastName": { "type": "string", "example": "last Name" },
        "birthDate": { "type": "string", "example": "Birth Day" },
        "phoneNumber": { "type": "string", "example": "09385667274" },
        "email": { "type": "string", "example": "email@mail.com" },
        "shebaNumber": { "type": "string", "example": "123123123123123" },
        "twitter": { "type": "string", "example": "twitter" },
        "linkedin": { "type": "string", "example": "linkedin" },
        "bugCrowd": { "type": "string", "example": "bugCrowd" },
        "password": { "type": "string", "example": "password" },
        "hackerOne": { "type": "string", "example": "hackerOne" },
        "description": { "type": "string", "example": "hackerOne" },
        "balance": { "type": "integer", "example": 0 }
      }
    },
    "CreateOrUpdateAdmin": {
      "type": "object",
      "properties": {
        "name": { "type": "string", "example": "کسری میباشد" },
        "phoneNumber": { "type": "string", "example": "09123456789" },
        "password": { "type": "string", "example": "123456789" }
      }
    },

    "UpdateAdminProfile": {
      "type": "object",
      "properties": {
        "name": { "type": "string", "example": "کسری میباشد" },
        "phoneNumber": { "type": "string", "example": "09123456789" },
        "password": { "type": "string", "example": "123456789" }
      }
    },
    "OrganizationsProjects": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "example": "canceled",
          "enum": ["approved_for_payment", "canceled", "approved"]
        },
        "cancelReason": {
          "type": "string",
          "example": "دلیل لغو اگر وجود دارد"
        }
      }
    }
  }
}
