{
  "swagger": "2.0",
  "info": {
    "title": "Bugdasht API - Hunters",
    "description": "Bugdasht Backend Restful-API ( Hunters Panel )",
    "version": "1.0"
  },
  "host": "localhost:3000",
  "basePath": "/v1/hunters",
  "schemes": ["http"],
  "paths": {
    "/auth/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "Register",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/Register" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 201,
                "data": {
                  "id": 5,
                  "firstName": "kasra",
                  "lastName": "khamesi",
                  "nationalCode": "022922991",
                  "birthDate": "Birth Date",
                  "phoneNumber": "09385667274",
                  "updatedAt": "2023-01-19T02:26:19.222Z",
                  "createdAt": "2023-01-19T02:26:19.222Z",
                  "token": {
                    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicGhvbmVOdW1iZXIiOiIwOTM4NTY2NzI3NCIsInR5cGUiOiJodW50ZXIiLCJpYXQiOjE2NzQwOTUxNzksImV4cCI6MTY3NzY5NTE3OX0.OWM9Druzvr9MyQjrQx3W-cQa3hi1Cdo9oYmJLUuxttM",
                    "expireAt": "2023-03-01T18:26:19.000Z"
                  }
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "Login",
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": { "$ref": "#/definitions/Login" }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "statusCode": 200,
                "data": {
                  "id": 1,
                  "profileImage": null,
                  "nationalCode": 22922991,
                  "nickName": null,
                  "firstName": "kasra",
                  "lastName": "khamesi",
                  "birthDate": "Birth Date",
                  "phoneNumber": "09385667274",
                  "email": null,
                  "shebaNumber": null,
                  "twitter": null,
                  "linkedin": null,
                  "bugCrowd": null,
                  "hackerOne": null,
                  "createdAt": "2023-01-19T02:24:46.000Z",
                  "updatedAt": "2023-01-19T02:24:46.000Z",
                  "token": {
                    "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvbmVOdW1iZXIiOiIwOTM4NTY2NzI3NCIsInR5cGUiOiJodW50ZXIiLCJpYXQiOjE2NzQwOTU0NTUsImV4cCI6MTY3NzY5NTQ1NX0.WwznDT1aViQeiygtsQSSRV1vXjXKBe6y0wN94f937F8",
                    "expireAt": "2023-03-01T18:30:55.000Z"
                  }
                },
                "error": null
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "examples": {
              "application/json": {
                "statusCode": 400,
                "data": null,
                "error": {
                  "message": "این یک خطا است",
                  "details": []
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "examples": {
              "application/json": {
                "statusCode": 422,
                "data": null,
                "error": {
                  "message": "اینپوت پیدا نشد",
                  "details": [{ "phoneNumber": ["شماره تلفن وارد نشده است"] }]
                }
              }
            }
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "http",
      "scheme": "bearer",
      "bearerFormat": "JWT",
      "in": "header"
    }
  },
  "definitions": {
    "Register": {
      "type": "object",
      "properties": {
        "firstName": { "type": "string", "example": "kasra" },
        "lastName": { "type": "string", "example": "khamesi" },
        "nationalCode": {
          "type": "number",
          "example": "022922991"
        },
        "birthDate": {
          "type": "string",
          "example": "Birth Date"
        },
        "password": {
          "type": "string",
          "example": "password"
        },
        "phoneNumber": { "type": "string", "example": "09385667274" }
      }
    },
    "Login": {
      "type": "object",
      "properties": {
        "phoneNumber": { "type": "string", "example": "09385667274" },
        "password": {
          "type": "string",
          "example": "password"
        }
      }
    }
  }
}
